### ISSUE TITLE
Observe multiple peers

### ISSUE THREAD

**Issue by guoger** [guoger/tape#43]
we should be able to observe multiple peers, to support semantics like "block is considered committed if it's done on >50% peers"

**Comment by SamYuan1990** [comment]
![image](https://user-images.githubusercontent.com/7820992/89039984-9012b180-d375-11ea-9be0-898106564edb.png)

so by design, it similar with Integrator for Observer, and a buffer channel there for the blocks and tx don't meet the `Latch`.
once it meets the `Latch` remove it.

```
Observer -> new block
if block in over Latched container(hash map? etc?), skip.
if block in waiting queue 
   if block meets Latch condition, move to over Latched container
otherwise, move block back to waiting queue, update Latched info.
```

Pls let me know if the design is fine.
